Aplikacija/IzaUgla/IzaUgla/Models/Dogadjaj.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.ComponentModel.DataAnnotations;

namespace IzaUgla.Models
{
    public class Dogadjaj
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [BsonElement("Naziv")]
        [Required]
        public string Naziv { get; set; }

        [BsonElement("Opis")]
        [Required]
        public string Opis { get; set; }

        [BsonElement("DatumVreme")]
        [Required]
        public DateTime VremeDatum { get; set; }

        //lokacija??
        [BsonElement("Ulica")]
        [Required]
        public string Ulica { get; set; }
        [BsonElement("Broj")]
 
        public decimal Broj { get; set; }
        [BsonElement("Opstina")]
        [Required]
        public string Opstina { get; set; }
        [BsonElement("Grad")]
        [Required]
        public string Grad { get; set; }




        [BsonElement("Tag")]
        [Display(Name = "Tag")]
        
        public IList<string> TagoviDogadjaja { get; set; }

        //kako povezati sa modelom u bazi
        public IList<Komentar> Komentari { get; set; }


        [BsonElement("ImageUrl")]
        [Display(Name = "Photo")]
        [DataType(DataType.ImageUrl)]
        [Required]
        public string ImageUrl { get; set; }
    }
}

Aplikacija/IzaUgla/IzaUgla/Controllers/DogadjajController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IzaUgla.Models;

namespace IzaUgla.Controllers
{
    public class DogadjajController : Controller
    {
        private readonly Services.DogadjajService dogadjajService;
        private readonly Services.KomentarService komentarService;
        private readonly Services.KorisnikService korisnikService;

        public DogadjajController(Services.DogadjajService dogadjajService,
                                  Services.KomentarService komentarService,
                                  Services.KorisnikService korisnikService)
        {
            this.dogadjajService = dogadjajService;
            this.komentarService = komentarService;
            this.korisnikService = korisnikService;
        }

       
        public ActionResult Index()
        {
            return View(dogadjajService.Get());
        }

       
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dogadjaj = dogadjajService.Get(id);

            if (dogadjaj == null)
            {
                return NotFound();
            }

            var sviKomentari = komentarService.Get();
            var sviKorisnici = korisnikService.Get();
            List<KomentarKorisnik> komentarikorisnika = new List<KomentarKorisnik>();

            foreach(Komentar k in sviKomentari)
            {
                if(k.Id_dogadjaja==dogadjaj.Id)
                {
                    KomentarKorisnik komentarKorisnik = new KomentarKorisnik();
                    komentarKorisnik.komentar = k;
                    var korisnik = sviKorisnici.Where(korisnik => korisnik.Id == k.Id_korisnika).FirstOrDefault();
                    if (korisnik != null)
                        komentarKorisnik.korisnik = korisnik;
                    komentarikorisnika.Add(komentarKorisnik);
                }
            }
            DogadjajKomentarKorisnik dogadjajKomentarKorisnik = new DogadjajKomentarKorisnik();
            dogadjajKomentarKorisnik.dogadjaj = dogadjaj;
            dogadjajKomentarKorisnik.komentarKorisnik = komentarikorisnika;

            return View(dogadjajKomentarKorisnik);
        }

      
        public ActionResult Create()
        {
            return View();
        }

      
        [HttpPost]
       
        public ActionResult Create(Dogadjaj dogadjaj)
        {
            if (ModelState.IsValid)
            {
                dogadjajService.Create(dogadjaj);
                return RedirectToAction(nameof(Index));
            }
            return View(dogadjaj);
        }

      
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dogadjaj = dogadjajService.Get(id);
            if (dogadjaj == null)
            {
                return NotFound();
            }
            return View(dogadjaj);
        }

       
        [HttpPost]
        
        public ActionResult Edit(string id, Dogadjaj dogadjaj)
        {
            if (id != dogadjaj.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                dogadjajService.Update(id, dogadjaj);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(dogadjaj);
            }
        }

       
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dogadjaj = dogadjajService.Get(id);
            if (dogadjaj == null)
            {
                return NotFound();
            }
            return View(dogadjaj);
        }

       
        [HttpPost, ActionName("Delete")]
       
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
                var dogadjaj = dogadjajService.Get(id);

                if (dogadjaj == null)
                {
                    return NotFound();
                }

                dogadjajService.Remove(dogadjaj.Id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Aplikacija/IzaUgla/IzaUgla/Controllers/KomentarController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IzaUgla.Models;

namespace IzaUgla.Controllers
{
    public class KomentarController : Controller
    {
        private readonly Services.KomentarService komentarService;
        private readonly Services.KorisnikService korisnikService;

        public KomentarController(Services.KomentarService komentarService, Services.KorisnikService korisnikService)
        {
            this.komentarService = komentarService;
            this.korisnikService = korisnikService;
        }
       
        public ActionResult Index()
        {
            return View(komentarService.Get());
        }

       
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var komentar = komentarService.Get(id);
            if (komentar == null)
            {
                return NotFound();
            }
            return View(komentar);
        }

      
        //public ActionResult CreateComment()
        //{
        //    return View();
        //}

        public ActionResult CreateComment(string _id)
        {
            Komentar k = new Komentar();

            if (_id != null)
            {
                k.Id_dogadjaja = _id;
            }
            return View(k);
        }


        [HttpPost]
       
        public ActionResult CreateComment(Komentar komentar)
        {
            //komentar.DatumVreme =
            var korisnici = korisnikService.Get();
            var korisnik = korisnici.Where(korisnik => korisnik.Username == komentar.Username).FirstOrDefault();
            if (korisnik.Password == komentar.Password)
            {
                komentar.Id_korisnika = korisnik.Id;
                komentar.DatumVreme = DateTime.Now;
                if (ModelState.IsValid)
                {
                    komentarService.Create(komentar);
                    return RedirectToAction("Details", "Dogadjaj", new { id = komentar.Id_dogadjaja });
                }
            }
            return View(komentar);
        }
       
        public ActionResult DeleteComment(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var komentar = komentarService.Get(id);
            if (komentar == null)
            {
                return NotFound();
            }
            return View(komentar);
        }

       


        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
               
                var komentar = komentarService.Get(id);

                if (komentar == null)
                {
                    return RedirectToAction("Index", "Dogadjaj");
                }

                komentarService.Remove(komentar.Id);

                return RedirectToAction("Index","Dogadjaj");
            }
            catch
            {
                return RedirectToAction("Index", "Dogadjaj");
            }
        }
    }
}

Aplikacija/IzaUgla/IzaUgla/Views/Dogadjaj/Create.cshtml
@model IzaUgla.Models.Dogadjaj

@{
    ViewData["Title"] = "Create";
}

<h4>Dogadjaj</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VremeDatum" class="control-label"></label>
                <input asp-for="VremeDatum" class="form-control" />
                <span asp-validation-for="VremeDatum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ulica" class="control-label"></label>
                <input asp-for="Ulica" class="form-control" />
                <span asp-validation-for="Ulica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Broj" class="control-label"></label>
                <input asp-for="Broj" class="form-control" />
                <span asp-validation-for="Broj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opstina" class="control-label"></label>
                <input asp-for="Opstina" class="form-control" />
                <span asp-validation-for="Opstina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grad" class="control-label"></label>
                <input asp-for="Grad" class="form-control" />
                <span asp-validation-for="Grad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Vrati se na pocetak</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Aplikacija/IzaUgla/IzaUgla/Views/Dogadjaj/Delete.cshtml
@model IzaUgla.Models.Dogadjaj

@{
    ViewData["Title"] = "Obriši dogadjaj";
    Layout = "_Layout";
}



<h3>Da li ste sigurni da želite da izbrišete dogadjaj?</h3>
<div>
    <h4>Dogadjaj</h4>
    <hr />
    <dl class="row">
      
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VremeDatum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VremeDatum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ulica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ulica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Broj)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Broj)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opstina)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opstina)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class="col-sm-10">
            <img src="@Url.Content(Model.ImageUrl)" class="img-thumbnail" alt="Image" />
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Vrati se nazad</a>
    </form>
</div>

Aplikacija/IzaUgla/IzaUgla/Views/Dogadjaj/Details.cshtml
@model IzaUgla.Models.DogadjajKomentarKorisnik

@{
    ViewData["Title"] = "Details";
}

<h1>Detalji o dogadjaju</h1>

<div>
    <h4>Dogadjaj</h4>
    <hr />
    <dl class="row">
     
      
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dogadjaj.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dogadjaj.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dogadjaj.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dogadjaj.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dogadjaj.VremeDatum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dogadjaj.VremeDatum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dogadjaj.Ulica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dogadjaj.Ulica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dogadjaj.Broj)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dogadjaj.Broj)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dogadjaj.Opstina)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dogadjaj.Opstina)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dogadjaj.Grad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dogadjaj.Grad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dogadjaj.ImageUrl)
        </dt>
        <dd class="col-sm-10">
            <img src="@Url.Content(Model.dogadjaj.ImageUrl)" class="img-thumbnail" alt="Image" />
        </dd>
    </dl>
</div>
    @Html.ActionLink("Dodaj komentar","CreateComment","Komentar", new { _id = Model.dogadjaj.Id })
<div>
    @foreach(KomentarKorisnik kk in Model.komentarKorisnik)
    {
        <div>
            <p>
                @kk.korisnik.Username
            </p>
            <p>
                @kk.komentar.KomentarData
            </p>
            @Html.ActionLink("Obriši komentar", "DeleteComment", "Komentar", new { id = kk.komentar.Id })
        </div>
    }
</div>
<div>
    @Html.ActionLink("Izmeni", "Edit", new {  id = Model.dogadjaj.Id }) |
    <a asp-action="Index">Vrati se nazad</a>
</div>

Aplikacija/IzaUgla/IzaUgla/Views/Dogadjaj/Edit.cshtml
@model IzaUgla.Models.Dogadjaj

@{
    ViewData["Title"] = "Izmeni dogadjaj";
}

<h1>Izmeni dogadjaj</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VremeDatum" class="control-label"></label>
                <input asp-for="VremeDatum" class="form-control" />
                <span asp-validation-for="VremeDatum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ulica" class="control-label"></label>
                <input asp-for="Ulica" class="form-control" />
                <span asp-validation-for="Ulica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Broj" class="control-label"></label>
                <input asp-for="Broj" class="form-control" />
                <span asp-validation-for="Broj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opstina" class="control-label"></label>
                <input asp-for="Opstina" class="form-control" />
                <span asp-validation-for="Opstina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grad" class="control-label"></label>
                <input asp-for="Grad" class="form-control" />
                <span asp-validation-for="Grad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sačuvaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Vrati se nazad</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Aplikacija/IzaUgla/IzaUgla/Views/Dogadjaj/Index.cshtml
@model IEnumerable<IzaUgla.Models.Dogadjaj>

@{
    ViewData["Title"] = "Index";
}

<h1>Prikaz dogadjaja</h1>

<p>
    <a asp-action="Create">Dodaj dogadjaj</a>
</p>
<table class="table">
    <thead>
        <tr>
         
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VremeDatum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ulica)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Broj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opstina)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model == null) return; 
@foreach (var item in Model) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VremeDatum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ulica)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Broj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opstina)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grad)
            </td>
            <td>
                @if (item.ImageUrl != null)
                {
                    <img src="@Url.Content(item.ImageUrl)" class="img-thumbnail" alt="Image" />
                }
            </td>
            <td>
                @Html.ActionLink("Izmeni", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalji", "Details", new { id = item.Id }) |
                @Html.ActionLink("Obrisi", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>