Aplikacija/IzaUgla/IzaUgla/Controllers/DogadjajController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IzaUgla.Models;

namespace IzaUgla.Controllers
{
    public class DogadjajController : Controller
    {
        private readonly Services.DogadjajService dogadjajService;
        private readonly Services.KomentarService komentarService;
        private readonly Services.KorisnikService korisnikService;

        public DogadjajController(Services.DogadjajService dogadjajService,
                                  Services.KomentarService komentarService,
                                  Services.KorisnikService korisnikService)
        {
            this.dogadjajService = dogadjajService;
            this.komentarService = komentarService;
            this.korisnikService = korisnikService;
        }

       
        public ActionResult Index()
        {
            return View(dogadjajService.Get());
        }

       
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dogadjaj = dogadjajService.Get(id);

            if (dogadjaj == null)
            {
                return NotFound();
            }

            var sviKomentari = komentarService.Get();
            var sviKorisnici = korisnikService.Get();
            List<KomentarKorisnik> komentarikorisnika = new List<KomentarKorisnik>();

            foreach(Komentar k in sviKomentari)
            {
                if(k.Id_dogadjaja==dogadjaj.Id)
                {
                    KomentarKorisnik komentarKorisnik = new KomentarKorisnik();
                    komentarKorisnik.komentar = k;
                    var korisnik = sviKorisnici.Where(korisnik => korisnik.Id == k.Id_korisnika).FirstOrDefault();
                    if (korisnik != null)
                        komentarKorisnik.korisnik = korisnik;
                    komentarikorisnika.Add(komentarKorisnik);
                }
            }
            DogadjajKomentarKorisnik dogadjajKomentarKorisnik = new DogadjajKomentarKorisnik();
            dogadjajKomentarKorisnik.dogadjaj = dogadjaj;
            dogadjajKomentarKorisnik.komentarKorisnik = komentarikorisnika;

            return View(dogadjajKomentarKorisnik);
        }

      
        public ActionResult Create()
        {
            return View();
        }

      
        [HttpPost]
       
        public ActionResult Create(Dogadjaj dogadjaj)
        {
            if (ModelState.IsValid)
            {
                dogadjajService.Create(dogadjaj);
                return RedirectToAction(nameof(Index));
            }
            return View(dogadjaj);
        }

      
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dogadjaj = dogadjajService.Get(id);
            if (dogadjaj == null)
            {
                return NotFound();
            }
            return View(dogadjaj);
        }

       
        [HttpPost]
        
        public ActionResult Edit(string id, Dogadjaj dogadjaj)
        {
            if (id != dogadjaj.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                dogadjajService.Update(id, dogadjaj);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(dogadjaj);
            }
        }

       
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dogadjaj = dogadjajService.Get(id);
            if (dogadjaj == null)
            {
                return NotFound();
            }
            return View(dogadjaj);
        }

       
        [HttpPost, ActionName("Delete")]
       
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
                var dogadjaj = dogadjajService.Get(id);

                if (dogadjaj == null)
                {
                    return NotFound();
                }

                dogadjajService.Remove(dogadjaj.Id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Aplikacija/IzaUgla/IzaUgla/Controllers/KorisnikController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IzaUgla.Models;

namespace IzaUgla.Controllers
{
    public class KorisnikController : Controller
    {
        private readonly Services.KorisnikService korisnikService;

        public KorisnikController(Services.KorisnikService korisnikService)
        {
            this.korisnikService = korisnikService;
        }

        // GET: KorisnikController
        public ActionResult Index()
        {
            return View(korisnikService.Get());
        }

        // GET: KorisnikController/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = korisnikService.Get(id);
            if (korisnik == null)
            {
                return NotFound();
            }
            return View(korisnik);
        }

        // GET: KorisnikController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KorisnikController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Korisnik korisnik)
        {
            if (ModelState.IsValid)
            {
                korisnikService.Create(korisnik);
                return RedirectToAction(nameof(Index));
            }
            return View(korisnik);
        }

        // GET: KorisnikController/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = korisnikService.Get(id);
            if (korisnik == null)
            {
                return NotFound();
            }
            return View(korisnik);
        }

        // POST: KorisnikController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, Korisnik korisnik)
        {
            if (id != korisnik.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                korisnikService.Update(id, korisnik);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(korisnik);
            }
        }

        // GET: Cars/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = korisnikService.Get(id);
            if (korisnik == null)
            {
                return NotFound();
            }
            return View(korisnik);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
                var korisnik = korisnikService.Get(id);

                if (korisnik == null)
                {
                    return NotFound();
                }

                korisnikService.Remove(korisnik.Id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Aplikacija/IzaUgla/IzaUgla/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Iza ugla</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
               
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand align-content-end" asp-area="" asp-controller="Korisnik" asp-action="Index">Korisnici</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand align-content-end" asp-area="" asp-controller="Dogadjaj" asp-action="Index">Dogadjaji</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - IzaUgla - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>